version: "3.8"

services:
  django:
    build:
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./config:/config
    env_file:
      - .env.local
      # Uncomment this for prod.
      # - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
