# Generated by Django 5.0.7 on 2025-02-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_pending_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='pending_transaction',
        ),
        migrations.CreateModel(
            name='TransactionRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveSmallIntegerField(choices=[(0, ' Any'), (1, 'Sonic'), (2, 'Base')])),
                ('user_address', models.CharField(max_length=255)),
                ('flow', models.PositiveSmallIntegerField(choices=[(0, 'Swap')], default=0)),
                ('data', models.JSONField()),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_reason', models.CharField(max_length=255, null=True)),
                ('transaction_details', models.JSONField(null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_requests', to='chat.conversation')),
            ],
        ),
    ]
