# Generated by Django 5.0.7 on 2025-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_pending_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequests',
            name='signed_tx_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionrequests',
            name='tool_call_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrequests',
            name='flow',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Swap'), (1, 'Silo Lending Deposit'), (2, 'Silo Lending Withdraw'), (3, 'Stake Sonic')], default=0),
        ),
    ]
